name: http_throttle
version: 1.0.2-dev
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/http_throttle
description: HTTP client middleware that throttles requests.
environment:
  sdk: ">=1.13.0 <2.0.0-dev.infinity"
dependencies:
  http: ">=0.9.0 <0.12.0"
  pool: ">=1.0.0 <2.0.0"
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
